name: Upload Package

on:
  workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Extract release tag name
        id: get_release_tag
        run: |
          echo "RELEASE_TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/mgkyawkolwin/PhoneKeyPadInputConverter/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: dotnet build --configuration Release ./src/InputConverters/InputConverters.csproj

      - name: Create the package
        run: |
          # Update the .csproj file with the release tag name
          dotnet pack --configuration Release ./src/InputConverters/InputConverters.csproj

      - name: Find the .nupkg file
        id: find_nupkg
        run: |
          # Find the .nupkg file in the Release directory
          NUPKG_FILE=$(ls ./src/InputConverters/bin/Release/*.nupkg)
          echo "NUPKG_FILE=${NUPKG_FILE}" >> $GITHUB_ENV

      - name: Nuget Add Source
        run: |
          dotnet nuget add source --username mgkyawkolwin --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/mgkyawkolwin/index.json"

      - name: Publish the package to GPR
        run: |
          dotnet nuget push "./src/InputConverters/bin/Release/"${{ env.NUPKG_FILE }} --api-key ${{secrets.GITHUB_TOKEN}} --source "github"
          # dotnet nuget push "./src/InputConverters/bin/Release/*.nupkg" --source "https://nuget.pkg.github.com/mgkyawkolwin/PhoneKeypadInputConverter/index.json"